name: lint
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install black
        run: |
          python -m pip install --upgrade pip
          pip install black
      - name: Lint with black
        run: |
          black --check --diff
      - name: Install flawfinder
        run: |
          sudo apt install flawfinder
      - name: Lint with flawfinder
        run: |
          flawfinder unishox2_module.c